# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_MainWindow(object):
    def conexdb(self):
        con = pymysql.connect(db='crud_db', user='root', passwd='mecatronicastark', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("CONEXION","Conexion:  REALIZADA")
        else:
            self.messagebox("CONEXION","Conexion:  NO VALIDA")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def save(self):
        id_code = self.plainTextEdit.toPlainText()
        Nombre = self.plainTextEdit_2.toPlainText()
        Apellido = self.plainTextEdit_3.toPlainText()
        Descripcion = self.plainTextEdit_4.toPlainText()
        Materia = self.plainTextEdit_5.toPlainText()
        insert = (id_code, Nombre, Apellido, Descripcion, Materia)
        print(insert)
        con = pymysql.connect(db='crud_db', user='root', passwd='mecatronicastark', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "INSERT INTO crud_tb (id_code, Nombre, Apellido, Descripcion, Materia) VALUES " + str(insert)
        data = cur.execute(sql)
        if(data):
            self.messagebox("EXITO !", " LOS DATOS DE LA TABLA \n HAN SIDO GUARDADOS")
        else:
            self.messagebox("FALLO", "LOS DATOS DE LA TABLA NO \n HAN SIDO GUARDADOS")

    def buscar(self):
        id_code = self.plainTextEdit.toPlainText()
        db = pymysql.connect(db='crud_db', user='root', passwd='mecatronicastark', host='localhost', port=3306, autocommit=True)
        cursor = db.cursor()
        cursor.execute("SELECT * FROM crud_tb WHERE id_code = '" + str(id_code) + "'")
        data = cursor.fetchall()
        if(data):
            for tp in data:
                self.plainTextEdit.setPlainText(""+tp[0])
                self.plainTextEdit_2.setPlainText(""+tp[1])
                self.plainTextEdit_3.setPlainText(""+tp[2])
                self.plainTextEdit_4.setPlainText(""+tp[3])
                self.plainTextEdit_5.setPlainText(""+tp[4])
        else:
            self.messagebox("INFO", "INGRESE EL ID_CODE")

    def update(self):
        id_code = self.plainTextEdit.toPlainText()
        Nombre = self.plainTextEdit_2.toPlainText()
        Apellido = self.plainTextEdit_3.toPlainText()
        Descripcion = self.plainTextEdit_4.toPlainText()
        Materia = self.plainTextEdit_5.toPlainText()
        con = pymysql.connect(db='crud_db', user='root', passwd='mecatronicastark', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "UPDATE crud_tb SET Nombre=%s, Apellido=%s, Descripcion=%s, Materia=%s WHERE id_code=%s"
        data = cur.execute(sql, (Nombre, Apellido, Descripcion, Materia, id_code))
        if(data):
            self.messagebox("EXITO !", "LA INFORMACION FUE ACTUALIZADA")
        else:
            self.messagebox(" INFORMACION", "NO SE HAN MODIFICADO LOS CAMPOS")

    def delete(self):
        id_code = self.plainTextEdit.toPlainText()
        con = pymysql.connect(db='crud_db', user='root', passwd='mecatronicastark', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "DELETE FROM crud_tb WHERE id_code=%s"
        data = cur.execute(sql, (id_code))
        if(data):
            self.messagebox("EXITO !", "LA INFORMACION FUE BORRADA")
        else:
            self.messagebox("FALLO !", "LA INFORMACION NO FUE BORRADA")

    def clear(self):
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_5.setPlainText("")


    def setupUi(self, MainWindow):
        self.conexdb()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(150, 100, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(150, 160, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 230, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(150, 220, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 290, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(150, 280, 621, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 410, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(150, 400, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 482, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.save)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 480, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.update)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 480, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.delete)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(510, 480, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.clear)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 480, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.buscar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " BASES DE DATOS MYSQL"))
        self.label.setText(_translate("MainWindow", "      REGISTRO DE ESTUDIANTES"))
        self.label_2.setText(_translate("MainWindow", "ID_CODE"))
        self.label_3.setText(_translate("MainWindow", "NOMBRE"))
        self.label_4.setText(_translate("MainWindow", "APELLIDO"))
        self.label_5.setText(_translate("MainWindow", "DESCRIP."))
        self.label_6.setText(_translate("MainWindow", "MATERIA"))
        self.pushButton.setText(_translate("MainWindow", "GUARDAR"))
        self.pushButton_2.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.pushButton_3.setText(_translate("MainWindow", "ELIMINAR"))
        self.pushButton_4.setText(_translate("MainWindow", "BORRAR"))
        self.pushButton_5.setText(_translate("MainWindow", "BUSCAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

